wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1673977635.903477
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      3:
      - 13
      - 23
      4: 3.8.15
      5: 0.13.7
      6: 4.17.0
      8:
      - 5
api:
  desc: null
  value: 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
data_path:
  desc: null
  value: data/train-v4.tsv
dependence:
  desc: null
  value: true
inter:
  desc: null
  value:
  - gpt
model:
  desc: null
  value: ckiplab/gpt2-base-chinese
ra:
  desc: null
  value: 50
sample_per_batch:
  desc: null
  value: 5
save:
  desc: null
  value: prompt_davinci_emotion
setting:
  desc: null
  value: 1
